### ISSUE TITLE
Incorrect 5.19 kernel, Ubuntu 22.04.2 LTS Support period.

### ISSUE THREAD

**Issue by ogandojose** [canonical/ubuntu.com#13079] opened 2023-08-09 22:59 UTC
The 5.19 Kernel support period is already over, and the website shows that 5.19 Kernel support on 22.04.2 LTS will be for 3 years.

Either the site wants to show 

a) that we will be supporting Jammy for an additional 3 years, using the 5.15 kernel.
b) or the site has the wrong dates (Just like 5.13 on Focal was stated).

---
*Reported from: https://ubuntu.com/about/release-cycle

**Comment by ksacilotto** [comment] 2023-08-18 13:08
Likely a duplicate of #13030.

**Closed** 2024-12-09 08:26 UTC
