### ISSUE TITLE
22.04.4 and other download links redirect only to releases.ubuntu.com

### ISSUE THREAD

**Issue by quantum-mirror** [canonical/ubuntu.com#13707] opened 2024-03-30 03:35 UTC
Hi,

If I want to download an iso image from Hungary from the official ubuntu 
page for example 
https://ubuntu.com/download/desktop/thank-you?version=22.04.4&architecture=amd64 
it by default redirects to releases.ubuntu.com not to an official local 
mirror.

wget output:

> wget 
> https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-desktop-amd64.iso
> --2024-03-19 13:01:39-- 
> https://releases.ubuntu.com/22.04.4/ubuntu-22.04.4-desktop-amd64.iso
> Resolving releases.ubuntu.com (releases.ubuntu.com)... 91.189.91.124, 
> 185.125.190.37, 185.125.190.40, ...
> Connecting to releases.ubuntu.com 
> (releases.ubuntu.com)|91.189.91.124|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 5017356288 (4.7G) [application/x-iso9660-image]
> Saving to: 'ubuntu-22.04.4-desktop-amd64.iso.3'

Would you be so kind and fix this please.

Thanks in advance!

More info at the mailing list:  https://lists.ubuntu.com/archives/ubuntu-mirrors/2024-March/thread.html

**Comment by brlin-tw** [comment] 2024-04-10 16:36
I can reproduce this issue, however, this seems to be a duplicate of #13343.

**Comment by akbarkz** [comment] 2024-04-29 06:15
Closing this issue since it's a duplicate of https://github.com/canonical/ubuntu.com/issues/13343 which will be addressed soon.

**Closed by akbarkz** 2024-04-29 06:15 UTC
